modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPLv3"
issueTrackerURL="https://github.com/xaidee/emcompat/issues/" #optional

[[mods]] #mandatory
modId="emcompat" #mandatory
version="0.1.0" #mandatory
displayName="Enhanced Mushrooms: Compatabilities" #mandatory
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/emcompat/files" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/emcompat" #optional
logoFile="logo.png" #optional
authors="Xaidee, Digital Pear, and ExuberantOctopus" #optional
description='''
A Forge mod adding compatability between the Enhanced Mushrooms mod and other mods that add mushrooms and fungi to the game.
'''
[[dependencies.emcompat]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.emcompat]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
